# Syntax highlighting
markdown:  redcarpet
highlighter:  pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone: Europe/Greece
locale:  en_us
name: Anna 
title: Photorgasms
tagline: 'photos and more'
description: 'aspiring photographer - art appreciator'
url: http://sunbliss.github.io
google_analytics:
rss:                 rss feed url
baseurl: '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Anna Prigkipaki
  url:            	 http://sunbliss.github.io
  flickr:          sunbliss
 

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"